### ISSUE TITLE
Scrapers do not take into account hand edited data

### ISSUE THREAD

**Issue by pallih** [gogn-in/polls#1]
like in commit cac24fd5d339b52fffe36de62b46893c733c544f

which will get overwritten on next run

**Comment by flother** [comment]
I don't see this repo as being the place to keep original data. Any data we want to include should be taken from an external, trustworthy, public source. This repo shouldn't be the primary data source, it should be the method of collating the data sources, with proof of their provenance.

In the case of the data we have so far, from Gallup and MMR, we scrape from the primary sources. Unfortunately for the two sources we're missing, Fréttablaðið/Stöð 2 and Félagsvísindastofnun, there is no public source that we can scrape. So we need to contribute to one — one that is public, trustworthy, and provably correct.

I think the best option we have for this are the tables of opinion polls on the Wikipedia pages for Alþingi elections — e.g. [_Icelandic parliamentary election, 2017_](https://en.wikipedia.org/wiki/Icelandic_parliamentary_election,_2017#Opinion_polls) and [_Icelandic parliamentary election, 2013_](https://en.wikipedia.org/wiki/Icelandic_parliamentary_election,_2013#Opinion_polls). We should be contributing to those — cleaning them up, adding missing polls, etc.

**Comment by flother** [comment]
Closing in favour of #2.
